'use client'

import type { LucideIcon } from 'lucide-react'
import {
  Atom,
  Award,
  BadgeCheck,
  BookOpen,
  Brain,
  Briefcase,
  Bus,
  CalendarDays,
  ChartNoAxesCombined,
  ClipboardList,
  Compass,
  Cpu,
  FileText,
  Globe,
  GraduationCap,
  HandHeart,
  HeartHandshake,
  Landmark,
  Layers,
  Lightbulb,
  LocateFixed,
  Mail,
  Medal,
  Microscope,
  Newspaper,
  Palette,
  Phone,
  Puzzle,
  Scale,
  School,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  Smartphone,
  Sparkles,
  Sprout,
  Stars,
  Telescope,
  Trophy,
  UserCheck,
  UserRound,
  Users,
  VenetianMask,
  WalletCards,
  Waves,
  Zap,
} from 'lucide-react'

const ICON_MAP: Record<string, LucideIcon> = {
  '🎓': GraduationCap,
  '📚': BookOpen,
  '📖': BookOpen,
  '🤖': Cpu,
  '🧠': Brain,
  '🐍': Cpu,
  '📊': ChartNoAxesCombined,
  '🏗️': Layers,
  '⚡': Zap,
  '🥽': Compass,
  '🪐': Stars,
  '🌍': Globe,
  '🏆': Trophy,
  '📍': LocateFixed,
  '📞': Phone,
  '✉️': Mail,
  '🌐': Globe,
  '📱': Smartphone,
  '📅': CalendarDays,
  '🏫': School,
  '👩‍🎓': Users,
  '👩‍🏫': UserCheck,
  '🎯': BadgeCheck,
  '💡': Lightbulb,
  '🤝': HandHeart,
  '☄️': Sparkles,
  '📐': Scale,
  '🔬': Microscope,
  '🌊': Waves,
  '🦕': VenetianMask,
  '⚛️': Atom,
  '🏦': Landmark,
  '💳': WalletCards,
  '🌟': Award,
  '🎨': Palette,
  '⚽': Trophy,
  '👕': Shirt,
  '👗': Shirt,
  '👔': Shirt,
  '👘': Shirt,
  '🏃': UserRound,
  '🛍️': ShoppingBag,
  '🚌': Bus,
  '👩‍✈️': ShieldCheck,
  '💼': Briefcase,
  '📜': BookOpen,
  '🌱': Sprout,
  '🔭': Telescope,
  '🏅': Medal,
  '🌏': Globe,
  '🧩': Puzzle,
  '👨‍👩‍👧': HeartHandshake,
  '📋': ClipboardList,
  '📰': Newspaper,
  '📄': FileText,
}

type SchoolIconProps = {
  token?: string
  size?: number
  className?: string
}

export default function SchoolIcon({ token, size = 20, className }: SchoolIconProps) {
  const Icon = (token && ICON_MAP[token]) || Sparkles
  return <Icon size={size} strokeWidth={2} className={className} aria-hidden="true" />
}
